name: Test Action

on:
  push:
    branches:
    - main
    - staging
  workflow_dispatch:

env:
  staging: 1
  main: 2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - run: echo $GITHUB_REF_NAME
      
      - run: env 
